name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "🎉 GitHub Action is working in QTM-CICD-test!"
        
      - name: Check testng-results.xml exists
        run: |
          if [ ! -f "results/Scenario1.xml" ]; then
            echo "❌ File does not exist!"
          exit 1
          fi
          echo "✅ File found:"
          ls -lh results/Scenario1.xml

      - name: Upload Junit Results to QMetry
        run: |
          echo "Uploading Scenario1.xml..."
           curl --silent --show-error --write-out "\nStatus: %{http_code}\nResponse:\n%{response_body}" \
            --location 'https://testmanagement.qmetry.com/rest/import/createandscheduletestresults/1' \
            --header 'project: AT' \
            --header 'apikey: pt7itF28wVMONoU6LzEuPmdef1AMzSCuAm7byDGw' \
            --form entityType=JUNIT \
            --form file=@results/Scenario1.xml
